server:
  port: 8080

zuul:
  routes:
    bot-service_messages:
      path: /messages/**
      url: http://localhost:4081/messages/
    bot-service_response:
      path: /response/**
      url: http://localhost:4081/response/
            
ribbon:
  eureka:
    enabled: false
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
